Add two BUFR YAMLs for efclam and nexrad data
NOAA-EMC/RDASApp pull request #102
Opened 2024-07-12 16:52 UTC by PraveenKumar-NOAA

This PR adds two ioda-converters YAML for the NEXRAD and EFCLAM BUFR data.

The following two files are new:

rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
rrfs-test/IODA/yaml/bufr_ncep_efclam.yaml

The validation for the NEXRAD output obs is performed in the following https://github.com/NOAA-EMC/RDASApp/issues/58.
The validation for the EFCLAM data was performed in the following https://github.com/NOAA-EMC/RDASApp/issues/76.

The test-data will be added separately to the RRFS test-data directory on Hera.

2024-07-12 18:04 UTC, TingLei-NOAA commented
@PraveenKumar-NOAA   Can we add a certain doc block in those yaml files?  including, like which executable would be used for them?

2024-07-12 20:00 UTC, MatthewMorris-NOAA requested changes
Looks good, but there was a typo in one of the yaml files.

2024-07-12 20:00 UTC, MatthewMorris-NOAA commented on rrfs-test/IODA/yaml/bufr_ncep_efclam.yaml
> +          longName: "Satelliate Identifier"
Typo

2024-07-15 15:18 UTC, SamuelDegelia-NOAA commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +            query: "*/SCID"
Just curious what these variables are and if we need them? They seem to be an index number of some kind.

2024-07-16 17:09 UTC, delippi reviewed
Hi @PraveenKumar-NOAA, My main concern is with the scaling of DIST125M. I don't think that should be scaled. All of my other comments were suggestions about units. Other than that, everything seems to be okay.

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +              - scale: 1000
Any reason that DIST125M is being scaled by 1000?

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +          longName: "Unfolding Velocity (to compute Nyqvist frequency)"
Typo: Nyquist velocity

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +          units: "m"
Should we just put "125m" for the units?

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +          longName: "Height Of Antenna Above Ground"
can we put units here?

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_nexrad.yaml
> +          #units: "m s-1"
I think m/s are the correct units here. This can be uncommented.

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_efclam.yaml
> +          units: "1"
Should units be "%"?

2024-07-16 17:09 UTC, delippi commented on rrfs-test/IODA/yaml/bufr_ncep_efclam.yaml
> +          units: "1"
Should units be "%"?

2024-07-16 18:21 UTC, PraveenKumar-NOAA commented
> @PraveenKumar-NOAA Can we add a certain doc block in those yaml files? including, like which executable would be used for them?

@TingLei-NOAA it is preferred to add this to YAML file. I will create a separate document and share with you all.

2024-07-16 18:50 UTC, delippi commented
Hi @PraveenKumar-NOAA, I see you made an update to scale DIST125M by 125 now so it is in units of m. What I meant was that I don't know if it should be scaled at all. I'm thinking it might be best to leave it unscaled since I don't know what JEDI is expecting the units to be. I believe GSI has a switch where it can use either 125 and 250 as the scaling factor for this data. I'm not sure how it actually decides which to use though. So this DIST125M variable is effectively just the gate number and when you scale it by 125m/250m it becomes the gateRange as it is currently named. I wonder if we just change the gateRange name to gateNumber or just the name from the bufr DIST125M and leave it in units of 125m.

@ShunLiu-NOAA do you have any thoughts?

2024-07-16 20:38 UTC, PraveenKumar-NOAA commented
> Hi @PraveenKumar-NOAA, I see you made an update to scale DIST125M by 125 now so it is in units of m. What I meant was that I don't know if it should be scaled at all. I'm thinking it might be best to leave it unscaled since I don't know what JEDI is expecting the units to be. I believe GSI has a switch where it can use either 125 and 250 as the scaling factor for this data. I'm not sure how it actually decides which to use though. So this DIST125M variable is effectively just the gate number and when you scale it by 125m/250m it becomes the gateRange as it is currently named. I wonder if we just change the gateRange name to gateNumber or just the name from the bufr DIST125M and leave it in units of 125m.
> 
> @ShunLiu-NOAA do you have any thoughts?

@delippi thanks. It is scaled now and this is whole point of validation. This is the JEDI expectation and that is why I changed the  name to 'gateRange' and unit to 'meter' for DIST125M. I also spoke with JCSDA before coming up this name for DIST125M. I only found DIST125M Mnemonics in the bufr data, if there were other distance variable like DIST250M  they needed to be change accordingly.

2024-07-16 20:55 UTC, delippi commented
> > Hi @PraveenKumar-NOAA, I see you made an update to scale DIST125M by 125 now so it is in units of m. What I meant was that I don't know if it should be scaled at all. I'm thinking it might be best to leave it unscaled since I don't know what JEDI is expecting the units to be. I believe GSI has a switch where it can use either 125 and 250 as the scaling factor for this data. I'm not sure how it actually decides which to use though. So this DIST125M variable is effectively just the gate number and when you scale it by 125m/250m it becomes the gateRange as it is currently named. I wonder if we just change the gateRange name to gateNumber or just the name from the bufr DIST125M and leave it in units of 125m.
> > @ShunLiu-NOAA do you have any thoughts?
> 
> @delippi thanks. It is scaled now and this is whole point of validation. This is the JEDI expectation and that is why I changed the name to 'gateRange' and unit to 'meter' for DIST125M. I also spoke with JCSDA before coming up this name for DIST125M. I only found DIST125M Mnemonics in the bufr data, if there were other distance variable like DIST250M they needed to be change accordingly.

@PraveenKumar-NOAA, thanks for that explanation. I think it makes sense how you have it then.

2024-07-23 15:07 UTC, PraveenKumar-NOAA commented
@ShunLiu-NOAA @delippi @TingLei-NOAA @MatthewMorris-NOAA @SamuelDegelia-NOAA let me know if you have any more questions about this PR.

2024-07-23 15:16 UTC, TingLei-NOAA commented
@PraveenKumar-NOAA  My only question was about documentation.  You mentioned you would create a separate doc (though i think in-line doc would be easier, but  maybe jedi likes a "clean" yaml).  Did I miss your updates following it?  Thanks

2024-07-23 15:27 UTC, PraveenKumar-NOAA commented
> @PraveenKumar-NOAA My only question was about documentation. You mentioned you would create a separate doc (though i think in-line doc would be easier, but maybe jedi likes a "clean" yaml). Did I miss your updates following it? Thanks

@TingLei-NOAA I think it is not a good idea to include that in the YAML. We are doing same thing for the global YAMLs. However, I am preparing a separate document on how to use these YAMLs and generate the test data. I will present this with an example to the RRFS/ [3D]-RTMA users.

2024-07-23 15:32 UTC, TingLei-NOAA commented
@PraveenKumar-NOAA  I think with this PR, maybe you could create a README.txt and add some simple description in it, which could also be used by other files later in this dir.

2024-07-23 15:33 UTC, ShunLiu-NOAA commented
As Ting suggested, could you provide a link to this PR or add create a wiki page to document these details?

2024-07-23 15:52 UTC, PraveenKumar-NOAA commented
> As Ting suggested, could you provide a link to this PR or add create a wiki page to document these details?

@TingLei-NOAA @ShunLiu-NOAA I will add the document to the wiki or a README.txt file separately, after I show this to the users with an example.

2024-08-05 14:46 UTC, TingLei-NOAA approved these changes

2024-08-05 14:55 UTC, MatthewMorris-NOAA approved these changes

2024-08-05 17:12 UTC, SamuelDegelia-NOAA approved these changes

2024-08-09 15:57 UTC, PraveenKumar-NOAA commented
@ShunLiu-NOAA @TingLei-NOAA @MatthewMorris-NOAA @SamuelDegelia-NOAA FYI: also added a document to RDASApp wiki on how to run BUFR2IODA converter with these YAMLs.

2024-08-29 14:57 UTC, PraveenKumar-NOAA commented
@ShunLiu-NOAA please let me know the another test data information you want to run with these YAMLs.

2024-08-29 15:30 UTC, SamuelDegelia-NOAA commented
@PraveenKumar-NOAA The prepbufr data for the new MPAS test case are linked into RDASApp after running `RDASApp/rrfs-test/scripts/link_mpasjedi_expr.sh`. Once that script has been run (no arguments or anything needed), you can find the prepbufr data in `RDASApp/expr/mpas_2024052700/data/obs/bufr`. Hopefully that contains the data you need to test these bufr2ioda yamls.

2024-08-30 17:49 UTC, merged