update the mpas_2024052700 case to use mpasout files
NOAA-EMC/RDASApp pull request #161
Opened 2024-09-10 04:23 UTC by guoqing-noaa

2024-09-11 00:54 UTC, guoqing-noaa commented
@Junjun-NOAA @delippi 
If you are interested, you may try rerunning your case using the mpasout files in this PR to see whether you can get wind increments from the assimilation of T obs.

2024-09-11 02:08 UTC, delippi commented
@guoqing-noaa, yes, I already started. I was able to assimilate winds and get temperature increments (slightly different from what others are doing). I will have some suggestions in a review that I will work on tomorrow.

2024-09-11 13:00 UTC, delippi requested changes
I found one small change that is needed. In `setup_experiment.sh` the path to `static.nc` is slightly incorrect. I noted what it should be in that file. Other than that this PR looks good to me. I did run everything using the new backgrounds and I can confirm that I was able to assimilate wind observations and was able to have increments of temperature. I was going to share my results, because I thought they were strange, but I just realized there might be issues with `data/obs`.

Edit: Actually, I think there are just issues with `data/obs/ioda_mesonet.nc` which I didn't test (due to incorrect data types and some other things--perhaps an old yaml was used to create that?). The aircraft data is correct.

2024-09-11 13:00 UTC, delippi commented on rrfs-test/scripts/setup_experiment.sh
> +  ln -snf ${YOUR_PATH_TO_RDASAPP}/fix/expr_data/${TEST_DATA}/bkg/static.nc static.nc
`ln -snf ${YOUR_PATH_TO_RDASAPP}/fix/expr_data/${TEST_DATA}/bkg/static.nc static.nc` should be `ln -snf ${YOUR_PATH_TO_RDASAPP}/fix/expr_data/${TEST_DATA}/static.nc static.nc` (the `bkg` removed)

2024-09-13 01:30 UTC, TingLei-NOAA commented on rrfs-test/scripts/link_mpasjedi_expr.sh
> +ln -snf ${RDASApp}/fix/expr_data/${exprname}/static.nc static.nc
could those static files in the source location be added  qualifiers of  grid-related labels?

2024-09-13 15:15 UTC, HuiLiu-NOAA commented
@guoqing-noaa : just tested the new case and got an error with the files:

17: !!! Hint: group interp_c1b_to_c0a_002
 17:        |-> cmp_1
 17:           |-> common
 17:              |-> bumploc_401km11levels_nicas
 17: Abort(1) on node 17 (rank 17 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 17
 18: !!! NetCDF error in netcdf_inquire_grp on task #000019: NetCDF: No group found.

2024-09-19 15:59 UTC, ShunLiu-NOAA commented
@guoqing-noaa Do you have a chance to address @HuiLiu-NOAA and @TingLei-NOAA's comments?

2024-09-19 19:58 UTC, guoqing-noaa commented
@ShunLiu-NOAA Thanks for the reminder. I will address Hui and Ting's comments.

But the big concern is, as discussed with @SamuelDegelia-NOAA in this thread, the transition to mpasout files changed the bumploc files. This is unexpected and we will need more time to dig into this issue.

2024-09-24 17:32 UTC, TingLei-NOAA commented
@guoqing-noaa  Could you point to your run dirs to create bump files using restart files (old) and mpasout files (current) respectively?  This will allow us to reproduce your results and join the investigation into this issue.

2024-09-25 16:12 UTC, guoqing-noaa commented
> @guoqing-noaa Could you point to your run dirs to create bump files using restart files (old) and mpasout files (current) respectively? This will allow us to reproduce your results and join the investigation into this issue.

@TingLei-NOAA Thanks for helping with this issue.

I ran the mpasout version on Jet and it is at:
`/lfs5/BMC/wrfruc/gge/RDASApp/expr/mpas_2024052700`   

I ran the restart version on Hera and it is at:
`/scratch1/BMC/wrfruc/gge/RDASApp/expr/mpas_2024052700`  

If you want to reproduce the case comparison,  you can check two versions of RDASApp: NOAA-EMC:develop and guoqing-noaa:mpasout, generate bumploc files respectively, run the single obs jedi case, plot the increments.

I can also regenerate them at a later time (maybe weekend).

2024-09-26 11:25 UTC, TingLei-NOAA commented
@guoqing-noaa   Thanks. I had copied them to my account and will see what the differences are.

2024-09-26 15:17 UTC, TingLei-NOAA commented
@guoqing-noaa  My runs showed identical results using mpasout or restart files. 
What I did is as follows:
```
I changed the bumploc.yaml for jet case to be used for hera case with another variables changes which I believe shouldn't affect results (but we could check on it later if needed) . 
The two files are in https://github.com/TingLei-NOAA/RDASApp/tree/feature/for-test/rrfs-test/example-files. 
I ran both cases on hera using the executable: mpasjedi_error_covariance_toolbox.x from https://github.com/NOAA-EMC/RDASApp/pull/175.  I used it because its executables are already ready on hera.   
Using "diff" to compare the generated "bumploc_401km11levels_nicas_local*.nc" from the two runs and no differences were found. 
```

This confirms our pre-assumption that using mpasout or restart files should not change the output in the nicas files (while, there could be still other possibility like the differences in the vertical coor. to cause differences), which is , at least, understandable. 

So, the differences you found might come from other differences.  For further investigation, you could run those two cases also on the same machine , like hera. 
(my copy of your jet case on hera is /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-guoqing/dr-jet/mpas_2024052700).
 
 We could first see you could get the same comparison results when running them on the same machine.

2024-10-04 15:24 UTC, ShunLiu-NOAA commented
> @guoqing-noaa My runs showed identical results using mpasout or restart files. What I did is as follows:
> 
> ```
> I changed the bumploc.yaml for jet case to be used for hera case with another variables changes which I believe shouldn't affect results (but we could check on it later if needed) . 
> The two files are in https://github.com/TingLei-NOAA/RDASApp/tree/feature/for-test/rrfs-test/example-files. 
> I ran both cases on hera using the executable: mpasjedi_error_covariance_toolbox.x from https://github.com/NOAA-EMC/RDASApp/pull/175.  I used it because its executables are already ready on hera.   
> Using "diff" to compare the generated "bumploc_401km11levels_nicas_local*.nc" from the two runs and no differences were found. 
> ```
> 
> This confirms our pre-assumption that using mpasout or restart files should not change the output in the nicas files (while, there could be still other possibility like the differences in the vertical coor. to cause differences), which is , at least, understandable.
> 
> So, the differences you found might come from other differences. For further investigation, you could run those two cases also on the same machine , like hera. (my copy of your jet case on hera is /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-guoqing/dr-jet/mpas_2024052700).
> 
> We could first see you could get the same comparison results when running them on the same machine.

@guoqing-noaa do you get a chance to take a look at this?

2024-10-10 14:12 UTC, guoqing-noaa commented
Convert this to draft PR as there are lingering issues and we may update to the 66 levels directly and skip this PR.

2024-10-15 15:34 UTC, SamuelDegelia-NOAA commented
Does #194 supersede this PR? Should we close this?

2024-10-16 02:15 UTC, guoqing-noaa commented
> Does #194 supersede this PR? Should we close this?

Yes and good suggestion, @SamuelDegelia-NOAA 

@ShunLiu-NOAA, I quoted @TingLei-NOAA's replies below and thanks @TingLei-NOAA for the testing!

Yes, as Ting suggested, the differences came from the RDASApp hash I used is different from that was used to generate the staged bumploc files.  The `mpasout` and `restart` files themselves will not cause any differences in the bumploc files.

> @guoqing-noaa My runs showed identical results using mpasout or restart files. What I did is as follows:
> 
> ```
> I changed the bumploc.yaml for jet case to be used for hera case with another variables changes which I believe shouldn't affect results (but we could check on it later if needed) . 
> The two files are in https://github.com/TingLei-NOAA/RDASApp/tree/feature/for-test/rrfs-test/example-files. 
> I ran both cases on hera using the executable: mpasjedi_error_covariance_toolbox.x from https://github.com/NOAA-EMC/RDASApp/pull/175.  I used it because its executables are already ready on hera.   
> Using "diff" to compare the generated "bumploc_401km11levels_nicas_local*.nc" from the two runs and no differences were found. 
> ```
> 
> This confirms our pre-assumption that using mpasout or restart files should not change the output in the nicas files (while, there could be still other possibility like the differences in the vertical coor. to cause differences), which is , at least, understandable.
> 
> So, the differences you found might come from other differences. For further investigation, you could run those two cases also on the same machine , like hera. (my copy of your jet case on hera is /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-guoqing/dr-jet/mpas_2024052700).
> 
> We could first see you could get the same comparison results when running them on the same machine.

2024-10-16 03:27 UTC, ShunLiu-NOAA commented
Yes. We should close this one. @guoqing-noaa I did mention in this PR that we may consider keeping the restart file name.

2024-10-16 03:43 UTC, guoqing-noaa commented
Close this PR as discussed. Thanks!

2024-10-16 03:43 UTC, closed without merging